### ISSUE TITLE
persist state of progress through the workshop

### ISSUE THREAD

**Issue by sethvincent** [adventuretron/adventuretron#7]
adventuretron needs to store which challenges have been finished in a workshop. maybe in a leveldb, maybe just in a json file.

**Comment by nickpeihl** [comment]
PouchDB maybe?

**Comment by sethvincent** [comment]
So far I've tried pouchdb and choo-persist and got indexeddb errors I didn't understand. Trying out level-browserify right now to see if the same thing comes up.

**Comment by nickpeihl** [comment]
I don't have any working experience with PouchDB but @timwis managed to get PouchDB working with choo working in [enviar](https://github.com/timwis/enviar). 

But leveldb would be cool, too.

**Comment by sethvincent** [comment]
adventuretron@0.0.13 now persists state!

Went with level-browserify for now. Might revisit that decision later, but it seems like it will work ok.
