### ISSUE TITLE
Module version mismath

### ISSUE THREAD

**Issue by stefanjudis** [adventuretron/adventuretron#8]
I really like this idea here but unfortunately I can not even start the project.

```
/Users/stefanjudis/Projects/adventuretron/node_modules/bindings/bindings.js:83 Uncaught Error: Module version mismatch. Expected 50, got 51.
```

Any ideas... I was trying to solve it with electron-rebuild with no luck so far.

My environment is:

node v7.1.0

And i followed these instructions:

```
mkdir example-workshop
cd example-workshop
adventuretron new -t "Example Workshop"
```

And `npm start` doesn't work because of the exception.

**Comment by sethvincent** [comment]
Thanks @stefanjudis!

This is related to electron being built with one version, then run with another (I think that's what it is anyway).

I'll do some troubleshooting and may come back to you with questions about your environment / things to try.

One thing worth trying:

In the example-workshop directory try deleting the node modules folder with `rm -rf node_modules` then reinstall dependencies with `npm install`

**Comment by stefanjudis** [comment]
Drop and install didn't help. :( 

I did several electron projects so far and didnt run in this common issue yet. Will also dig more tomorrow. :)

**Comment by sethvincent** [comment]
Good to know. Thank you.

**Comment by sethvincent** [comment]
Alright. I also had trouble with electron-rebuild.

I was able to get things working again by running this after `adventuretron new`:

```
npm rebuild --runtime=electron --target=1.4.6 --disturl=https://atom.io/download/atom-shell --build-from-source
```

I may add that as the last command executed by the `adventuretron new` command.

**Comment by sethvincent** [comment]
ok with latest adventuretron it now runs the `npm rebuild` command in my last comment as part of `adventuretron new` so running:

```sh
adventuretron new
npm start
```

should just work.

**Comment by stefanjudis** [comment]
Fixed. Thanks. :) I'll start playing around with it. ;)

**Comment by sethvincent** [comment]
Cool! This project is still somewhat new, so there may be other issues. I'm happy to help troubleshoot anything that comes up.

**Comment by stefanjudis** [comment]
No worries. :) 

I want to build a talk around this. So I think you'll see me more often here filing issues and handing in PR's in the future. ;)

Really like the idea!
